version: "3.7"
services:
  fastapi:
      build: ./app
      ports:
        - "8000:8000"
      depends_on:
        - rabbitmq
        - redis
      volumes:
        - "./app:/app"


  rabbitmq:
    image: "bitnami/rabbitmq:latest"
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/bitnami"

  redis:
    image: "bitnami/redis:latest"
    environment:
      - REDIS_PASSWORD=password123
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "tanx-task"
    ports:
      - "5432:5432"
    volumes:
    - ./database:/var/lib/postgresql

volumes:
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local
