version: "3.7"
services:
  fastapi:
      build: ./app
      ports:
        - "8000:8000"
      # depends_on:
      #   - rabbitmq
      #   - redis
      volumes:
        - "./app:/app"


  # rabbitmq:
  #   image: "bitnami/rabbitmq:3.7"
  #   ports:
  #     - "4369:4369"
  #     - "5672:5672"
  #     - "25672:25672"
  #     - "15672:15672"
  #   volumes:
  #     - "rabbitmq_data:/bitnami"

  # redis:
  #   image: "bitnami/redis:5.0.4"
  #   environment:
  #     - REDIS_PASSWORD=password123
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - "redis_data:/bitnami/redis/data"
